### PR TITLE
Add note with updates to README

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by eed3si9n** [comment]
sbt-sequential is actually a macro that allows you to code in imperative-looking code (just like sbt 0.13), although it doesn't actually support most of Scala syntax.
Whereas sequential task that I added was what Mark suggested, which is much weaker version of it, essentially a list of keys.

**Comment by dwijnand** [comment]
If I revise the messaging to be more in line with that, would you be interested in putting this information in the readme?

**Comment by dwijnand** [comment]
ping

**Comment by eed3si9n** [comment]
> If I revise the messaging to be more in line with that, would you be interested in putting this information in the readme?

Sure why not.

**Comment by dwijnand** [comment]
@eed3si9n Updated. WDYT? (Happy to continue revising).

**Comment by eed3si9n** [comment]
LGTM

**Pull request merged**
